import type { NextPage } from 'next'
import Head from 'next/head'
import { navLinks } from '../utils/data'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import TopBar from '../components/TopBar'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Video Class Filter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <TopBar />
      </main>

      <footer className={styles.footer}>

      </footer>
    </div>
  )
}

export default Home
